### ISSUE TITLE
EMFILE in writemarkdown

### ISSUE THREAD

**Issue by glasser** [jlord/offline-issues#15]
By default you can only have 256 open files at a time on OSX.  `writemarkdown` tries to write all files in parallel, so eg `ulimit -n 256; offline-issues meteor/meteor` will crash like this:

```
$ ./node_modules/.bin/offline-issues meteor/meteor
Wrote data

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/Users/glasser/Projects/Meteor/offline-issues/node_modules/offline-issues/src/templates/markdown.hbs'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.openSync (/Users/glasser/Projects/Meteor/offline-issues/node_modules/offline-issues/node_modules/cpr/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.readFileSync (fs.js:290:15)
    at /Users/glasser/Projects/Meteor/offline-issues/node_modules/offline-issues/src/writemarkdown.js:15:21
    at Array.forEach (native)
    at writemarkdown (/Users/glasser/Projects/Meteor/offline-issues/node_modules/offline-issues/src/writemarkdown.js:13:10)
    at /Users/glasser/Projects/Meteor/offline-issues/node_modules/offline-issues/src/index.js:129:7
    at /Users/glasser/Projects/Meteor/offline-issues/node_modules/offline-issues/node_modules/cpr/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:90:5
    at Object.oncomplete (fs.js:108:15)
```

As a workaround, you can just run `ulimit -n 5000` first or something, but maybe `writemarkdown` should use a mechanism to limit the number of parallel writes being done?

**Comment by glasser** [comment]
though actually looks like i'm pretty likely to hit the hourly API limit anyway, ah well

**Comment by jlord** [comment]
Ohhh, snap, didn't know about the limit but that makes sense. I guess it's best to just limit the number of writes :+1:

**Comment by jlord** [comment]
I just added https://github.com/jlord/offline-issues/commit/01f84d41aeddc82bd89c7aec9846adb83593b6a6 so that it will only ever try to do 250 max, which should be ok for the OS and the GitHub API.

It's not ideal if you truly want *all* issues however, but since this ☝️ error no longer happen I'm going to close this issue and open a new one about processing issues in batches.
