### ISSUE TITLE
Trouble running on Ubuntu

### ISSUE THREAD

**Issue by krlmlr** [jlord/offline-issues#19]
I have tried running the script on Ubuntu, but it kept exiting with a nonzero exit code until I finally asked

    nodejs $(which offline-issues)

Apparently, the Node.js executable is called differently on Ubuntu. (Source: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server)

For now I'm fine with the workaround, but I wonder if a cleaner solution exists.

**Comment by IonicaBizau** [comment]
@krlmlr Install Node from PPA. I always had problems when I installed it via `apt-get`. You can use [my script](https://github.com/IonicaBizau/dotfiles#applications) (`curl https://raw.githubusercontent.com/IonicaBizau/dotfiles/master/apps/node.sh | sh`), which actually does:

```sh
sudo apt-get install -y python-software-properties python g++ make
sudo add-apt-repository ppa:chris-lea/node.js -y
sudo apt-get update
sudo apt-get install nodejs -y
```

**Comment by jlord** [comment]
Hopefully @IonicaBizau's comment helped. I usually use the [distribution from NodeSource](https://github.com/nodesource/distributions#deb) but yeah, it can be confusing to install Node on Ubutunu. 

I tested it this morning and it was working on my VM so I'll close this one out for now ✨

**Comment by IonicaBizau** [comment]
[`nvm`](https://github.com/creationix/nvm) is also a good way to install Node.js and keep it up-to-date. I recently switched on it. 😁
