### ISSUE TITLE
Coding style.

### ISSUE THREAD

**Issue by Tjoosten** [jlord/offline-issues#26]
Hi,

I was wondering to maybe add missing semicolons? 

current code: 

```
var fs = require('fs')
var mkdirp =  require('mkdirp')
var handlebars = require('handlebars')
var marked = require('marked')
var cpr = require('cpr')
var path = require('path')
```

Because it looks odd in webstorm and phpstorm without semicolons. If you want i can fix this.

**Comment by jlord** [comment]
Hi! Thanks for the offer but I prefer no semicolons so they're intentionally left out :sparkles:
